INSERT INTO bamazonDB.products (item_id, product_name, department_name, price, stock_quantity) VALUES (1, "Some Book","Books", 24.25, 10);
INSERT INTO bamazonDB.products (product_name, department_name, price, stock_quantity) VALUES ("Lipstick", "Beauty", 14.99, 100);
INSERT INTO bamazonDB.products (product_name, department_name, price, stock_quantity) VALUES ("Sofa", "Home & Kitchen", 249.99, 18);
INSERT INTO bamazonDB.products (product_name, department_name, price, stock_quantity) VALUES ("Shampoo", "Health & Personal Care", 8.99, 200);
INSERT INTO bamazonDB.products (product_name, department_name, price, stock_quantity) VALUES ("Tablet", "Electronics", 499.99, 5);
INSERT INTO bamazonDB.products (product_name, department_name, price, stock_quantity) VALUES ("Rare Jewellery", "Accessories", 1999.99, 1);
INSERT INTO bamazonDB.products (product_name, department_name, price, stock_quantity) VALUES ("Watch", "Accessories", 450, 3);
INSERT INTO bamazonDB.products (product_name, department_name, price, stock_quantity) VALUES ("Tool Kit","Tools & Home Improvement", 29.99, 30);
INSERT INTO bamazonDB.products (product_name, department_name, price, stock_quantity) VALUES ("Mini Fridge", "Home & Kitchen", 50, 7);
INSERT INTO bamazonDB.products (product_name, department_name, price, stock_quantity) VALUES ("Another Book", "Books", 29.95, 9);